name: Java

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'
          cache: 'gradle'
      - run: ./gradlew jar --no-daemon
      - run: cp app/build/libs/app.jar Calculon.jar
      - uses: actions/upload-artifact@v3
        with:
          name: Calculon
          path: Calculon.jar
          if-no-files-found: error

# TODO (result is very big ~150 MB)
# jpackage --type app-image -i /Users/simon/repos/Calculon/app/build/libs/ -n Calculon --main-class Calculon.App --main-jar app.jar

# couldn't get it working with modules, but will the result be smaller?
# jpackage --type app-image -i /Users/simon/repos/Calculon/app/src -n Calculon --module-path app --module Calculon.App