name: Release

on:
  push:
    # tags:
    #   - "**"

jobs:
  jar:
    name: Build Jar
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "20"
          cache: "gradle"
      - run: ./gradlew jar --no-daemon
      - run: cp app/build/libs/app.jar Calculon.jar
      - uses: actions/upload-artifact@v3
        with:
          name: Calculon-Jar
          path: Calculon.jar
          if-no-files-found: error
  release:
    needs: [jar]
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest] # [ubuntu-22.04, windows-latest, macos-latest]
    name: Release
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: Calculon-Jar
          path: app/build/libs/
      - working-directory: app/build/libs/
        run: cp Calculon.jar app.jar
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "20"
          cache: "gradle"
      # - name: Build Linux
      #   if: runner.os == 'Linux'
      #   run: |
      #     jpackage -i ./app/build/libs/ -n Calculon --main-class io.github.sj14.calculon.Calculon --main-jar app.jar --icon assets/calculon.png
      #     mv calculon_1.0_amd64.deb calculon_amd64.deb
      #     git status
      - name: Build Windows
        if: runner.os == 'Windows'
        run: |
          $env:APPVER=[int32](New-TimeSpan -Start (Get-Date "01/01/1970") -End (Get-Date)).TotalSeconds
          jpackage -i ./app/build/libs/ -n Calculon --main-class io.github.sj14.calculon.Calculon --main-jar app.jar --icon assets/calculon.ico --app-version $env:APPVER
          mv Calculon-$env:APPVER.exe Calculon.exe
          git status
      # - name: Build macOS
      #   if: runner.os == 'macos'
      #   run: |
      #     jpackage -i ./app/build/libs/ -n Calculon --main-class io.github.sj14.calculon.Calculon --main-jar app.jar --icon assets/calculon.icns
      #     mv Calculon-1.0.dmg Calculon.dmg
      #     git status
      # Upload to the workflow summary (useful when testing and disabling the 'push/tag' filter)
      - uses: actions/upload-artifact@v3
        name: Upload to workflow summary
        with:
          name: Calculon-${{ runner.os }}
          path: |
            Calculon.dmg
            calculon_amd64.deb
            Calculon.exe
      # - name: Upload to the release
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     files: |
      #       app/build/libs/Calculon.jar
      #       Calculon.dmg
      #       calculon_amd64.deb
      #       Calculon.exe
